version: '3.7'

services:
  nginx: 
    build: ./nginx 
    # volumes: 
    #   - static:/static
    ports: 
      - "80:80"
    depends_on:
      - backend 

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
     - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./my_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  sqlite_data:
