# Generated by Django 4.2.3 on 2023-08-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionyear',
            name='year',
        ),
    ]
